name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Do the build
      - name: build
        run: |
          ./build.sh

      # Publish test results
      - name: archive-test-reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: linux-test-results
          path: 'build/test-results'
          if-no-files-found: error

  build-windows:
    runs-on: windows-2019
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Do the build
      - name: build
        shell: cmd
        run: |
          call .\build.cmd

      # Publish test results
      - name: archive-test-reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: windows-test-results
          path: 'build/test-results'
          if-no-files-found: error
