# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          echo Building...
          ./build.sh

      # Publish test results
      - name: publish-report
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          check_name: Unit Test Results
          comment_title: Unit Test Statistics
          hide_comments: all but latest
          files: build/foo/tests/tests.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
