name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Do the build
      - name: build
        run: |
          sudo apt-get install xsltproc
          ./build.sh

      # Publish test results
      - name: Archive test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: 'build/**/*-tests.html'
          if-no-files-found: error # 'warn' or 'ignore' are also available

  build-windows:
    runs-on: windows-2019
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Do the build
      - name: build
        shell: cmd
        run: |
	  call .\build.cmd
